package PeerApp;


/**
* PeerApp/PeerPOATie.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PeerApp.idl
* Sunday, 29 October 2023 10:39:53 AM FJT
*/

public class PeerPOATie extends PeerPOA
{

  // Constructors

  public PeerPOATie ( PeerApp.PeerOperations delegate ) {
      this._impl = delegate;
  }
  public PeerPOATie ( PeerApp.PeerOperations delegate , org.omg.PortableServer.POA poa ) {
      this._impl = delegate;
      this._poa      = poa;
  }
  public PeerApp.PeerOperations _delegate() {
      return this._impl;
  }
  public void _delegate (PeerApp.PeerOperations delegate ) {
      this._impl = delegate;
  }
  public org.omg.PortableServer.POA _default_POA() {
      if(_poa != null) {
          return _poa;
      }
      else {
          return super._default_POA();
      }
  }
  public int setup (int max, String nextName)
  {
    return _impl.setup(max, nextName);
  } // setup

  public int startElection ()
  {
    return _impl.startElection();
  } // startElection

  public int message1 (int receivedMax)
  {
    return _impl.message1(receivedMax);
  } // message1

  public int message2 (int receivedLeft)
  {
    return _impl.message2(receivedLeft);
  } // message2

  public int announceLeader (String name, int max)
  {
    return _impl.announceLeader(name, max);
  } // announceLeader

  public int passCoordinator ()
  {
    return _impl.passCoordinator();
  } // passCoordinator

  private PeerApp.PeerOperations _impl;
  private org.omg.PortableServer.POA _poa;

} // class PeerPOATie
