package PeerApp;

/**
* PeerApp/PeerHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PeerApp.idl
* Sunday, 29 October 2023 10:39:53 AM FJT
*/

public final class PeerHolder implements org.omg.CORBA.portable.Streamable
{
  public PeerApp.Peer value = null;

  public PeerHolder ()
  {
  }

  public PeerHolder (PeerApp.Peer initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = PeerApp.PeerHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    PeerApp.PeerHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return PeerApp.PeerHelper.type ();
  }

}
