package PeerApp;


/**
* PeerApp/PeerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PeerApp.idl
* Sunday, 29 October 2023 10:39:53 AM FJT
*/

public interface PeerOperations 
{
  int setup (int max, String nextName);
  int startElection ();
  int message1 (int receivedMax);
  int message2 (int receivedLeft);
  int announceLeader (String name, int max);
  int passCoordinator ();
} // interface PeerOperations
