package PeerApp;


/**
* PeerApp/RegisterPOATie.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PeerApp.idl
* Sunday, 29 October 2023 10:39:53 AM FJT
*/

public class RegisterPOATie extends RegisterPOA
{

  // Constructors

  public RegisterPOATie ( PeerApp.RegisterOperations delegate ) {
      this._impl = delegate;
  }
  public RegisterPOATie ( PeerApp.RegisterOperations delegate , org.omg.PortableServer.POA poa ) {
      this._impl = delegate;
      this._poa      = poa;
  }
  public PeerApp.RegisterOperations _delegate() {
      return this._impl;
  }
  public void _delegate (PeerApp.RegisterOperations delegate ) {
      this._impl = delegate;
  }
  public org.omg.PortableServer.POA _default_POA() {
      if(_poa != null) {
          return _poa;
      }
      else {
          return super._default_POA();
      }
  }
  public int connect (String name)
  {
    return _impl.connect(name);
  } // connect

  private PeerApp.RegisterOperations _impl;
  private org.omg.PortableServer.POA _poa;

} // class RegisterPOATie
