package PeerApp;

/**
* PeerApp/RegisterHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PeerApp.idl
* Sunday, 29 October 2023 10:39:53 AM FJT
*/

public final class RegisterHolder implements org.omg.CORBA.portable.Streamable
{
  public PeerApp.Register value = null;

  public RegisterHolder ()
  {
  }

  public RegisterHolder (PeerApp.Register initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = PeerApp.RegisterHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    PeerApp.RegisterHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return PeerApp.RegisterHelper.type ();
  }

}
