package PeerApp;


/**
* PeerApp/RegisterOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PeerApp.idl
* Sunday, 29 October 2023 10:39:53 AM FJT
*/

public interface RegisterOperations 
{
  int connect (String name);
} // interface RegisterOperations
